"""Add signature model

Revision ID: 0e17c8d02380
Revises: 7f928e5052c2
Create Date: 2026-08-10 23:43:41.900034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e17c8d02380'
down_revision: Union[str, Sequence[str], None] = '7f928e5052c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soap_note_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soap_note_id'], ['soap_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_doctor_id'), 'signatures', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_index(op.f('ix_signatures_soap_note_id'), 'signatures', ['soap_note_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_soap_note_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_doctor_id'), table_name='signatures')
    op.drop_table('signatures')
    # ### end Alembic commands ###
