"""Add code_reference table

Revision ID: 0ea687c2397c
Revises: f6fc1f9c840c
Create Date: 2026-08-09 00:19:11.561670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea687c2397c'
down_revision: Union[str, Sequence[str], None] = 'f6fc1f9c840c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_reference',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_type', sa.Enum('ICD10', 'CPT', name='codetype'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_code_reference_code'), 'code_reference', ['code'], unique=False)
    op.create_index(op.f('ix_code_reference_code_type'), 'code_reference', ['code_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_reference_code_type'), table_name='code_reference')
    op.drop_index(op.f('ix_code_reference_code'), table_name='code_reference')
    op.drop_table('code_reference')
    # ### end Alembic commands ###
