"""Add sync_status to soap_notes

Revision ID: 254456495549
Revises: 0e17c8d02380
Create Date: 2026-08-14 15:36:34.633395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254456495549'
down_revision: Union[str, Sequence[str], None] = '0e17c8d02380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    syncstatus = sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='syncstatus')
    syncstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('soap_notes', sa.Column('sync_status', syncstatus, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soap_notes', 'sync_status')
    # ### end Alembic commands ###
