"""Add consultation sessions table

Revision ID: 5d0e26df850c
Revises: 52fedb8089b0
Create Date: 2026-07-13 12:41:30.978392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0e26df850c'
down_revision: Union[str, Sequence[str], None] = '52fedb8089b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'RECORDING', 'STOPPED', 'FINALIZED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_sessions_doctor_id'), 'consultation_sessions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consultation_sessions_id'), 'consultation_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_sessions_id'), table_name='consultation_sessions')
    op.drop_index(op.f('ix_consultation_sessions_doctor_id'), table_name='consultation_sessions')
    op.drop_table('consultation_sessions')
    # ### end Alembic commands ###
