"""Add retention tracking to audio metadata

Revision ID: 68e4ed0603e3
Revises: 2846ac90233a
Create Date: 2026-07-25 00:45:31.214788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e4ed0603e3'
down_revision: Union[str, Sequence[str], None] = '2846ac90233a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_metadata', sa.Column('retention_marked_for_deletion_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audio_metadata', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_metadata', 'deleted_at')
    op.drop_column('audio_metadata', 'retention_marked_for_deletion_at')
    # ### end Alembic commands ###
