"""Add code_suggestions table

Revision ID: 7f928e5052c2
Revises: 0ea687c2397c
Create Date: 2026-08-09 17:36:33.251581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7f928e5052c2'
down_revision: Union[str, Sequence[str], None] = '0ea687c2397c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soap_note_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_type', postgresql.ENUM('ICD10', 'CPT', name='codetype', create_type=False), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['soap_note_id'], ['soap_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_suggestions_id'), 'code_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_code_suggestions_soap_note_id'), 'code_suggestions', ['soap_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_suggestions_soap_note_id'), table_name='code_suggestions')
    op.drop_index(op.f('ix_code_suggestions_id'), table_name='code_suggestions')
    op.drop_table('code_suggestions')
    # ### end Alembic commands ###
