"""Add SOAPNote and SOAPSection models

Revision ID: f6fc1f9c840c
Revises: 7e9c5ebbe198
Create Date: 2026-08-08 13:35:58.271629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fc1f9c840c'
down_revision: Union[str, Sequence[str], None] = '7e9c5ebbe198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soap_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SIGNED', name='soapnotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['consultation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soap_notes_id'), 'soap_notes', ['id'], unique=False)
    op.create_index(op.f('ix_soap_notes_session_id'), 'soap_notes', ['session_id'], unique=True)
    op.create_table('soap_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soap_note_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Enum('SUBJECTIVE', 'OBJECTIVE', 'ASSESSMENT', 'PLAN', name='soapsectiontype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['soap_note_id'], ['soap_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soap_sections_id'), 'soap_sections', ['id'], unique=False)
    op.create_index(op.f('ix_soap_sections_soap_note_id'), 'soap_sections', ['soap_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soap_sections_soap_note_id'), table_name='soap_sections')
    op.drop_index(op.f('ix_soap_sections_id'), table_name='soap_sections')
    op.drop_table('soap_sections')
    op.drop_index(op.f('ix_soap_notes_session_id'), table_name='soap_notes')
    op.drop_index(op.f('ix_soap_notes_id'), table_name='soap_notes')
    op.drop_table('soap_notes')
    # ### end Alembic commands ###
