"""Make audio file_path nullable for retention cleanup

Revision ID: fba44024baa6
Revises: 254456495549
Create Date: 2026-08-14 17:13:23.393403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba44024baa6'
down_revision: Union[str, Sequence[str], None] = '254456495549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_metadata', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_metadata', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
